language: php

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - tidy

env:
  global:
    - DB=MYSQL
    - COMPOSER_ROOT_VERSION=1.x-dev
    - SS_ENVIRONMENT_TYPE="dev"

matrix:
  include:
    - php: 5.6
      env: PHPUNIT_TEST=1
      env: PHPCS_TEST=1
      ss: SS_VER=4.0
    - php: 7.0
      env: PHPUNIT_TEST=1
      ss: SS_VER=4.0
    - php: 7.1
      env: PHPUNIT_TEST=1
      ss: SS_VER=4.1
    - php: 7.2
      env: PHPUNIT_TEST=1
      ss: SS_VER=4.2

before_script:
# Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'always_populate_raw_post_data = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer
  - composer require silverstripe/framework $SS_VER
  - composer update

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/php; fi
  - if [[ $PHPCS_TEST ]]; then composer run lint; fi

after_failure:
  - php ./vendor/silverstripe/framework/tests/behat/travis-upload-artifacts.php --if-env BEHAT_TEST,ARTIFACTS_BUCKET,ARTIFACTS_KEY,ARTIFACTS_SECRET --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/ --artifacts-path ./artifacts/
